name: Remove ASN
description: Request to remove an ASN from the list due to false positive.
title: "[ASN Removal] <short description>"
labels:
  - asn
body:
  - type: input
    id: asn-remove
    attributes:
      label: ASN(s) to remove
      description: List the ASN(s) to remove (e.g. AS54321).
    validations:
      required: true
  - type: textarea
    id: remove-reason
    attributes:
      label: Reason for removal
      description: Explain why this ASN is a false positive (e.g. residential, not a VPN, etc).
    validations:
      required: true
  - type: textarea
    id: remove-evidence
    attributes:
      label: Evidence/documentation
      description: Links, references, or explanation supporting removal.
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context, screenshots, or information here.
    validations:
      required: false
